# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-08 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=200, verbose_name='图片网址')),
                ('book_name', models.CharField(max_length=200, verbose_name='书名')),
                ('writer', models.CharField(max_length=64, verbose_name='作者')),
                ('miaoshu', models.CharField(max_length=200, verbose_name='小说描述')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhangjie', models.CharField(max_length=64, verbose_name='章节目录')),
                ('text', models.TextField(verbose_name='小说正文')),
                ('book_id', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.Book')),
            ],
            options={
                'db_table': 'BookDetail',
            },
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('classify_id', models.IntegerField(primary_key=True, serialize=False)),
                ('classify_name', models.CharField(max_length=64, verbose_name='小说分类')),
            ],
            options={
                'db_table': 'classify',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='classify_id',
            field=models.ForeignKey(db_column='classify_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.Classify'),
        ),
    ]
