# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-12 05:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DingDan',
            fields=[
                ('dd_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('dingdan_number', models.CharField(default='15420000963810058', max_length=255)),
                ('is_pay', models.IntegerField(default=0)),
                ('book_id', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.Book')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dingdan',
            },
        ),
    ]
